package models;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "PRODUCTS")
@Getter @Setter @NoArgsConstructor
@AllArgsConstructor @ToString
@Schema(description = "Entidad que representa un producto")
public class Product {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id_products")
    @Schema(description = "Codigo del product", example = "1")
    private Long id;

    @Column(name = "name_product",length = 120, nullable = false)
    private String name;

    @Column(name = "slug_product", length = 140, nullable = false)
    private String slug;

    @Column(name = "desc_product", length = 2000)
    private String description;

    @Column(name = "price_product", precision = 12, scale = 2, nullable = false)
    private BigDecimal price;

    @Column(name = "stock_product", nullable = false)
    private Integer stock;

    @Column(name = "stock_critico_product",nullable = false)
    private Integer stockCritico;

    @Column(name = "featured_product")
    private Integer featuredProduct;

    @Column(name = "creates_at", columnDefinition = "TIMESTAMP WITH TIME ZONE")
    private OffsetDateTime createsAt;

    @Column(name = "updated_at", columnDefinition = "TIMESTAMP WITH TIME ZONE")
    private OffsetDateTime updatedAt;

    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    @JoinColumn(name = "id_category", nullable = false)
    @JsonBackReference("category-products")
    private Category category;

    @OneToMany(mappedBy = "product", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonManagedReference("product-images")
    private List<ProductImage> images = new ArrayList<>();

    @OneToMany(mappedBy = "product", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonManagedReference("product-reviews")
    private List<Review> reviews = new ArrayList<>();

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_discount")
    private Discount discount;

}


//CREATE TABLE products (
//        id_product    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//        name          VARCHAR(180) NOT NULL,
//slug          VARCHAR(160) UNIQUE,
//description   TEXT,
//price         NUMERIC(12,2) NOT NULL CHECK (price >= 0),
//stock         INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
//featured      BOOLEAN NOT NULL DEFAULT FALSE,
//created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
//updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
//);