package models;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.*;
import org.springframework.web.service.annotation.PatchExchange;

@Entity
@Table(name = "products")
@Getter @Setter @NoArgsConstructor
@AllArgsConstructor @ToString
@Schema(description = "Entidad que representa un producto")
public class Producto {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id_products")
    @Schema(description = "Codigo del product", example = "1")
    private Long idProduct;

    @Column(name = "nombre_producto", nullable = false)
    @NotBlank(message = "El campo nombre producto no puede ser vacio")
    @Schema(description = "Nombre del producto", example = "Silla Gamer")
    private String name;

    @Column(name = "slug_producto", nullable = false)
    @NotBlank(message = "El campo slug producto no puede ser vacio")
    @Schema(description = "Slug del producto", example = "mi-primera-entrada")
    private String slug;

    @Column(name = "descripcion_producto", nullable = false)
    @NotBlank(message = "El campo descrpcion producto no puede ser vacio")
    @Schema(description = "Descripcion del producto", example = "Producto con si")
    private String description;

    @Column(name = "price_products", nullable = false)
    @NotBlank(message = "El campo precio producto no puede ser vacio")
    @Schema(description = "Precio del producto", example = "3400")
    private Number price;

    @Column(name = "stock_products", nullable = false)
    @NotBlank(message = "El campo stock producto no puede ser vacio")
    @Schema(description = "Stock del producto", example = "Descripcion del producto estandar")
    private Number stock;

    @Column(name = "featured-products")
    @NotBlank(message = "El campo featured producto no puede ser vacio")
    @Schema(description = "")
    private Boolean featured;
    //debo de averiguar como conectar los created_at y updated_at

    public Producto(String name, String slug, String description, Number price, Number stock, Boolean featured){
        this.name=name;
        this.slug=slug;
        this.description=description;
        this.price=price;
        this.stock=stock;
        this.featured=featured;
    }

}


//CREATE TABLE products (
//        id_product    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
//        name          VARCHAR(180) NOT NULL,
//slug          VARCHAR(160) UNIQUE,
//description   TEXT,
//price         NUMERIC(12,2) NOT NULL CHECK (price >= 0),
//stock         INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
//featured      BOOLEAN NOT NULL DEFAULT FALSE,
//created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
//updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
//);